### ISSUE TITLE
Guzzle SSL certificate problem

### ISSUE THREAD

**Issue by abigail59** [ricbra/php-discogs-api-example#1]
Hi Richard,

I followed the instructions provided, but unfortunately get a Guzzle issue :

Uncaught exception 'GuzzleHttp\Ring\Exception\RingException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate' in C:\wamp\www\va2\toto\vendor\guzzlehttp\command\src\AbstractClient.php on line 171

Do you have any clue ?

Thx for your help

**Comment by ricbra** [comment]
Hi @abigail59 

Just did some quick Googling, maybe this solves your issue: http://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

Looks like a problem with your installation.
